// Generated by https://quicktype.io

export interface IData {
  data: Data;
}

export interface Data {
  episodes: Episodes;
  characters: Characters;
}

export interface Characters {
  results: CharactersResult[];
}

export interface CharactersResult {
  id: string;
  name: string;
  status: Status;
  species: Species;
  gender: Gender;
  image: string;
  created: Date;
  favorite?: boolean;
}

export enum Gender {
  Female = 'Female',
  Male = 'Male',
  Unknown = 'unknown',
}

export enum Species {
  Alien = 'Alien',
  Human = 'Human',
}

export enum Status {
  Alive = 'Alive',
  Dead = 'Dead',
  Unknown = 'unknown',
}

export interface Episodes {
  results: EpisodesResult[];
}

export interface EpisodesResult {
  name: string;
  episode: string;
}
